[package]
name = "nulconnect-helper"
version = "0.2.3"
edition = "2024"

[lib]
crate-type = ["rlib", "staticlib"]

[[bin]]
name = "nulconnect-helper"
path = "src/bin/nulconnect_helper.rs"

[[bin]]
name = "nulconnect-helper-service"
path = "src/bin/windows_service.rs"
required-features = ["windows-service"]

[profile.release]
lto = "thin"
strip = "symbols"
codegen-units = 1
panic = "abort"

[dependencies]
base64 = "0.22"
reqwest = { version = "0.12", default-features = false, features = ["blocking", "cookies", "json", "rustls-tls"] }
rsa = "0.9"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
thiserror = "2"
url = "2"
reatrust = { path = "../libreatrust" }
smoltcp = { version = "0.13.1", default-features = false, features = ["proto-ipv4", "socket-tcp", "socket-udp", "medium-ip", "alloc"] }

[features]
default = []
verbose-logs = ["reatrust/verbose-logs"]
windows-service = []

[target.'cfg(windows)'.dependencies]
libloading = "0.8"
windows-service = "0.8"
windows-sys = { version = "0.61", features = [
    "Win32_Foundation",
    "Win32_Security",
    "Win32_Security_Authorization",
    "Win32_Storage_FileSystem",
    "Win32_System_IO",
    "Win32_System_Pipes",
] }

[target.'cfg(not(windows))'.dependencies]
libc = "0.2"
tun-rs = { version = "2", features = ["interruptible"] }
